### ISSUE TITLE
contoh penggunaan

### ISSUE THREAD

**Issue by ridwanbejo** [nyankod/cpform#1]
Kang toni ini contoh penggunaan CPForm:

https://dl.dropboxusercontent.com/u/54840757/cpform.tar.gz

**Comment by gemblue** [comment]
Mantap kang..

Best Regards,
Ahmad Oriza Sahputra
Programmer & Writer - www.codepolitan.com | @Oriza_Sahputra
Programmer's News Update.

2015-07-05 8:34 GMT+07:00 ridwanfs notifications@github.com:

**Comment by ridwanbejo** [comment]
Itu di sebelah mana cara bikin footnotenya :D?

**Comment by gemblue** [comment]
Ane mah reply langsung dari email kang :p

Best Regards,
Ahmad Oriza Sahputra
Programmer & Writer - www.codepolitan.com | @Oriza_Sahputra
Programmer's News Update.

**Comment by ridwanbejo** [comment]
owh pantesan -_- kirain bisa disetting dari Githubnya

**Comment by gemblue** [comment]
Wehehehehe

On 7/5/15, ridwanfs notifications@github.com wrote:

> owh pantesan -_- kirain bisa disetting dari Githubnya
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/nyankod/cpform/issues/1#issuecomment-118570194

## 

Best Regards,
Ahmad Oriza Sahputra
Programmer & Writer - www.codepolitan.com | @Oriza_Sahputra
Programmer's News Update.

**Comment by yllumi** [comment]
sipsip. ane baru pegang laptop

**Comment by yllumi** [comment]
@ridwanbejo kayaknya emang harus dimasukin sama CInya yah, soalnya kita emang masih develop. ane langsung masukin aja yah CInya.

**Comment by ridwanbejo** [comment]
Yah bener juga kang, ane ga sempet bikin dokumentasinya
