### ISSUE TITLE
Set 'initial' in Field can be replaced by using 'value'

### ISSUE THREAD

**Issue by yllumi** [nyankod/cpform#3]
instead of like this:

```
$this->username = array(
                'fields' => 'TextField',
                'initial'=>'ridwanbejo',
                'config' => array(
                    'placeholder' => 'isi dengan name anda...',
                    'id' => 'name',
                ),
            );
```

the `'initial'` index can be placed in config as `'value'`, like this:

```
$this->username = array(
                'fields' => 'TextField',
                'config' => array(
                    'placeholder' => 'isi dengan name anda...',
                    'id' => 'name',
                    'value'=>'ridwanbejo',
                ),
            );
```

**Comment by ridwanbejo** [comment]
value fields in config array can used by user as well as data-\* attribute. The initial option will accommodate, the initialization for multichoice field, checkbox field, and radio field.

$this->username = array(
                'initials' => ['beach', 'mountaion', 'waterfall'],
                'fields' => 'ChoiceField',
                'config' => array(
                    'placeholder' => 'isi dengan name anda...',
                    'id' => 'name',
                    'value'=>'ridwanbejo',
                ),
            );

**Comment by yllumi** [comment]
Oh I see. Ok I get it now.
